name: PHP Composer

on: [push]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php-versions: ['7.1', '7.2', '7.3']
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}

      # Setup PHP environment.
      # Docs: https://github.com/shivammathur/setup-php/blob/master/README.md
      - name: Set up PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
        # extension-csv: mbstring, intl # (optional) specify the extensions you want to enable/install.
        # ini-values-csv: short_open_tag=On # (optional) specify custom php.ini values.
        # coverage: xdebug # (optional) specify coverage driver.
        # pecl: false # (optional) use PECL as fallback to install extensions.

      - name: Check PHP Version
        run: php -v

      - name: Check Composer Version
        run: composer -V

      - name: Check PHP Extensions
        run: php -m

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest


      - name: Run test suite
        run: composer run-script test

      - name: Run phpcs
        run: composer run-script cs-check
